# 线程池与RuntimeException

## 在ScheduledThreadPool中出现RuntimeException
简单测试
```java
public class ThreadPoolTest {
    private static final Logger logger = LoggerFactory.getLogger(ThreadPoolTest.class);

    private static AtomicInteger count = new AtomicInteger(0);
    private static class Task implements Runnable {
        @Override
        public void run() {
            logger.info("invoke Task.run()");
            count.incrementAndGet();
            int rem = count.intValue() % 3;
            logger.info(String.valueOf(100 / rem));
        }
    }

    public static void main(String[] args) {
        ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor();
        ses.scheduleWithFixedDelay(new Task(), 1000, 1000, TimeUnit.MILLISECONDS);
    }
}
```
运行后结果如下：
```
17:52:58.116 [pool-1-thread-1] INFO com.fifedu.kyxl.kse.ThreadPoolTest - invoke Task.run()
17:52:58.140 [pool-1-thread-1] INFO com.fifedu.kyxl.kse.ThreadPoolTest - 100
17:52:59.143 [pool-1-thread-1] INFO com.fifedu.kyxl.kse.ThreadPoolTest - invoke Task.run()
17:52:59.143 [pool-1-thread-1] INFO com.fifedu.kyxl.kse.ThreadPoolTest - 50
17:53:00.144 [pool-1-thread-1] INFO com.fifedu.kyxl.kse.ThreadPoolTest - invoke Task.run()
```
可以看出这里的RuntimeException并没有打印出来，因此**不仅是Spring Boot，线程池都会吃掉RuntimeException异常信息**

同时也可以看出 `Executors.newSingleThreadScheduledExecutor` 在遇到 `RuntimeException` 后唯一的线程就“死”了，自然以后的任务都不会执行了（但是这时主线程并未结束）。
> 换成 `Executors.newScheduledThreadPool(1)` 也是同样

改成如下（对异常进行捕获）后，则Task就可以一直执行下去了：
```java
public class ThreadPoolTest {
    private static final Logger logger = LoggerFactory.getLogger(ThreadPoolTest.class);

    private static AtomicInteger count = new AtomicInteger(0);
    private static class Task implements Runnable {
        @Override
        public void run() {
            logger.info("invoke Task.run()");
            count.incrementAndGet();
            int rem = count.intValue() % 3;
            try {
                logger.info(String.valueOf(100 / rem));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) {
        ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor();
        ses.scheduleWithFixedDelay(new Task(), 1000, 1000, TimeUnit.MILLISECONDS);
    }
}
```

## 在ThreadPoolExecutor中出现RuntimeException
**异常线程会重建（名字也一样）；任务依然会接着执行（除失败任务）。**
```java
public class ThreadPoolTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(ThreadPoolTest.class);

    private static LinkedBlockingQueue<Integer> INTEGERS = new LinkedBlockingQueue<>();

    static {
        for (int i = 0; i < 100; i++) {
            INTEGERS.add(i);
        }
    }

    private static class Task implements Runnable {
        @Override
        public void run() {
            Integer integer = INTEGERS.poll();
            if (integer != null) {
                if (integer % 12 == 11) {
                    throw new RuntimeException();
                }
                LOGGER.info("integer: {}", integer);
            }
        }
    }

    public static void main(String[] args) {
        ExecutorService es = Executors.newSingleThreadExecutor();
        for (int i = 0; i < 20; i++) {
            es.submit(new Task());
        }
        es.shutdown();
    }
}
```

```
15:04:32.457 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 0
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 1
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 2
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 3
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 4
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 5
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 6
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 7
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 8
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 9
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 10
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 12
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 13
15:04:32.463 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 14
15:04:32.464 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 15
15:04:32.464 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 16
15:04:32.464 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 17
15:04:32.464 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 18
15:04:32.464 [pool-1-thread-1] INFO ink.akira.re0jdk8.ThreadPoolTest - integer: 19
```
> 后面没有打印了，且已结束运行

可以看出，即使线程 `pool-1-thread-1` 在 `integer == 11` 时出现RuntimeException，后面仍然是 `pool-1-thread-1` 来执行。
