# Java的异常机制

## 异常的分类
Java的异常类如下：

![Java的异常](https://blog.jdk8.akira.ink/images/exception.png)

- Error为程序中的重大问题，一般会对程序的正常执行产生影响，默认由JVM处理。如：
    ```
    StackOverflowError
    OutOfMemoryError
    ```
- RuntimeException 为一类比较特殊的异常，其产生比较频繁，显示地捕获将对程序的运行效率及可读性产生影响，因此默认也交给JVM进行处理。如：
    ```
    NullPointerException
    ArithmeticException
    ClassCastException
    ArrayIndexOutOfBoundsException
    NumberFormatException
    ```
- 上面两种异常为非受检异常（不需要程序代码进行处理），其余的异常则为受检异常，需要在程序代码中进行捕获、抛出等处理（编译器也会进行检查）。

## 异常的处理
受检异常必须处理，

### 抛给方法调用方处理
即使用throws抛出异常给方法调用方处理

### 捕获并处理
即使用try-catch-finally流程进行处理。
- try:
    
    可能会产生异常的代码块。
- catch:

    对异常进行捕获。一般子异常先catch，父异常后catch。

- finally:

    不管有没有异常，都会执行的代码块。
    
1. 不管try块、catch块中是否有return语句，finally块都会执行。
2. finally块中的return语句会覆盖前面的return语句（try块、catch块中的return语句），所以如果finally块中有return语句，
编译器会报警告“finally block does not complete normally”和"return inside finally block"
3. 如果finally块中包含了return语句，即使前面的catch块重新抛出了异常，则调用该方法的语句也不会获得catch块重新抛出的异常，而是会得到finally块的返回值，并且不会捕获异常，且该方法无须再throws出异常。

## 自定义异常
异常在Java中也是类，因此也可以自定义异常类去继承Exception类或其它现有异常类。     


